//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace skps_services.Platforms.Android.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("skps_services.Platforms.Android.Resources.Languages.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At SKPS Services, we pride ourselves on delivering top-notch solutions through our team of expert technicians. Each service is meticulously handled by professionals who bring years of experience and specialized knowledge to the table. Whether it’s a routine maintenance task or a complex technical issue, our skilled technicians ensure that every job is completed with precision and care. Trust us to provide reliable and efficient services that meet the highest standards of quality and excellence..
        /// </summary>
        internal static string AboutService {
            get {
                return ResourceManager.GetString("AboutService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Service.
        /// </summary>
        internal static string AboutService_1 {
            get {
                return ResourceManager.GetString("AboutService_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Now.
        /// </summary>
        internal static string BookNow {
            get {
                return ResourceManager.GetString("BookNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Service.
        /// </summary>
        internal static string BookService {
            get {
                return ResourceManager.GetString("BookService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Your Service Now.
        /// </summary>
        internal static string BookServiceNow {
            get {
                return ResourceManager.GetString("BookServiceNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Us.
        /// </summary>
        internal static string CallUs {
            get {
                return ResourceManager.GetString("CallUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        internal static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Us.
        /// </summary>
        internal static string EmailUs {
            get {
                return ResourceManager.GetString("EmailUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        internal static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        internal static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Password Reset Email.
        /// </summary>
        internal static string PasswordReset {
            get {
                return ResourceManager.GetString("PasswordReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the email address you entered is associated with an account, you&apos;ll receive a link to reset your password shortly. Please check your inbox and follow the instructions in the email..
        /// </summary>
        internal static string PasswordText {
            get {
                return ResourceManager.GetString("PasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your Preffered Language.
        /// </summary>
        internal static string PrefferedLanguage {
            get {
                return ResourceManager.GetString("PrefferedLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        internal static string SelectLang {
            get {
                return ResourceManager.GetString("SelectLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your service.
        /// </summary>
        internal static string SelectService {
            get {
                return ResourceManager.GetString("SelectService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are a well-established furniture and home appliance store in Thirukazhukundram since 1980. We offer a wide range of brand new furniture, home appliances, and utensils for marriages, festivals, and events..
        /// </summary>
        internal static string ShopAbout {
            get {
                return ResourceManager.GetString("ShopAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sri Kannigaparameshwari Services.
        /// </summary>
        internal static string ShopName {
            get {
                return ResourceManager.GetString("ShopName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamil.
        /// </summary>
        internal static string Tamil {
            get {
                return ResourceManager.GetString("Tamil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Details.
        /// </summary>
        internal static string UserDetails {
            get {
                return ResourceManager.GetString("UserDetails", resourceCulture);
            }
        }
    }
}
